### ISSUE TITLE
messages are duplicated

### ISSUE THREAD

**Issue by sasha-tkachev** [benc-uk/htmx-go-chat#2]
I logged in to the live demo https://chat.benco.io/ from my main chrome and from an incognito window.
and seems the messages in the first session are duplicated once the new session was created
![image](https://github.com/benc-uk/htmx-go-chat/assets/3898216/921c60a6-b2af-411d-996f-d50b452ba12a)

**Comment by benc-uk** [comment]
It was created for fun and 99% as a learning exercise
